config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :books
  resources :rentals, :only => [:index, :new, :create]
  resources :users, :only => [:index, :edit, :update, :show]
  resources :logs

  get 'search_book', to: 'rentals#search_book', path: "/rentals/new/search_book"
  get 'get_info', to: 'books#get_info', path: "/books/new/get_info"
  get 'return', to: 'rentals#pre_return', path: "/rentals/return"
  get 'search_book', to: 'rentals#search_book', path: "/rentals/return/search_book"
  post 'rentals', to: 'rentals#post_return', path: "/rentals/return"

 root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rentals, inverse_of: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: {super_admin: 'super_admin', admin: 'admin', member: 'member'}

  validates :name, presence: true

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params[:user].permit(:role)
    end

    def set_book
      @user = User.find(params[:id])
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>ユーザー権限編集</h1>

<hr>

<% if ! @user.super_admin? %>
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.select :role, {"管理者" => "admin", "一般ユーザー" => "member"} %>
  <%= f.primary "確定" %>
<% end %>
<% else %>
  <p>super_adminユーザーは権限を変更できません。</p>
<% end %>

app/views/users/index.html.erb
<h1>登録ユーザー一覧</h1>

<hr>

<table class="table table-bordered table-hover">
  <thead>
     <tr class="info"><th>id</th><th>名前</th><th>権限</th><th>操作</th></tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
    <tr>
    <td><%= u.id %></td>
    <td><%= u.name %></td>
    <td><%= u.role %></td>
    <td>
    <center>
    <%= link_to user_path(u.id), class: "btn btn-info"  do %>
      <i class="glyphicon glyphicon-info-sign"></i>
    <% end %>
    <% if ! u.super_admin? %>
    <%= link_to edit_user_path(u.id), class: "btn btn-warning" do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
    <% end %>
    </center>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>ユーザー情報詳細</h1>

<hr>


<table class="table table-bordered">
  <tbody>
    <tr>
    <td width="100", class="info">id</td> <td><%= @user.id %></td>
    </tr>
    <tr>
    <td width="100", class="info">名前</td> <td><%= @user.name %></td>
    </tr>
    <tr>
    <td width="100", class="info">メールアドレス</td> <td><%= @user.email %></td>
    </tr>
    <tr>
    <td width="100", class="info">最終ログイン</td> <td><%= @user.current_sign_in_at.in_time_zone('Tokyo') %></td>
    </tr>
    <tr>
    <td width="100", class="info">ログイン回数</td> <td><%= @user.sign_in_count %></td>
  </tbody>
</table>