config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :books
  resources :rentals, :only => [:index, :new, :create]
  resources :users, :only => [:index, :edit, :update, :show]
  resources :logs

  get 'search_book', to: 'rentals#search_book', path: "/rentals/new/search_book"
  get 'get_info', to: 'books#get_info', path: "/books/new/get_info"
  get 'return', to: 'rentals#pre_return', path: "/rentals/return"
  get 'search_book', to: 'rentals#search_book', path: "/rentals/return/search_book"
  post 'rentals', to: 'rentals#post_return', path: "/rentals/return"

 root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :rentals, inverse_of: :book
  has_one :book_rental_info

  # バリデーション 以下の項目は空欄ではいけない
  validates :title, :author, :manufacturer, :publication_date, :isbn, :code, presence: true

  # codeはユニークな値でなければならない
  validates :code, uniqueness: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  load_and_authorize_resource
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @search = Book.search(params[:q])
    @books = @search.result.page(params[:page])
  end

  def show
  end

  def new
    @book = Book.new
  end

  def get_info

    res = Amazon::Ecs.item_search(params[:isbn],
         :search_index   => 'Books',
         :response_group => 'Medium',
         :country        => 'jp'
       )

    if res.nil?
      info = nil
    else
      info = {'Title' => res.first_item.get('ItemAttributes/Title'),
            'Author' => res.first_item.get('ItemAttributes/Author'),
            'Manufacturer' => res.first_item.get('ItemAttributes/Manufacturer'),
            'Publication_Date' => res.first_item.get('ItemAttributes/PublicationDate'),
            'S_Image' => res.first_item.get('MediumImage/URL'),
            'L_Image' => res.first_item.get('LargeImage/URL')
              }
    end
    render json: info
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      @book_info = BookRentalInfo.create(book_id: @book.id)
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    if @book.book_rental_info.is_rentaled == false
      @book.destroy
      redirect_to books_path
    else
      redirect_to books_path, notice: "その本は貸出中のため削除できません。"
    end
  end

  private
    def book_params
        params[:book].permit(:title, :author, :manufacturer, :publication_date, :isbn, :code, :image_url)
    end

    def set_book
      @book = Book.find(params[:id])
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>本の編集</h1>

<%= bootstrap_form_for(@book) do |f| %>
  <%= f.text_field :isbn %>
  <%= f.text_field :title %>
  <%= f.text_field :author %>
  <%= f.text_field :manufacturer %>
  <%= f.text_field :publication_date %>
  <%= f.text_field :code %>
  <%= f.primary "本を編集" %>
<% end %>

app/views/books/index.html.erb
<h1>蔵書一覧</h1>

<hr>

<div class="well">
<h4><b>書籍検索</b></h4>
<%= search_form_for @search do |f| %>
  <%= f.label :title_cont, 'タイトル' %>
  <%= f.text_field :title_cont %>
  <%= button_tag( :class => "btn btn-success") do %>
    <i class="glyphicon glyphicon-search"></i> 検索
  <% end %>
<% end %>
</div>

<br>

<%= page_entries_info @books %>

<table class="table table-hover">
  <thead>
     <tr class="info">
       <th>ID</th>
      <th>タイトル</th>
      <th>著者</th>
      <th>出版社</th>
      <th>発売日</th>
        <% if can? :create, Book %>
        <th width="150">
          <div align="right">
          <%= link_to new_book_path, :class => "btn btn-primary" do %>
          <i class="glyphicon glyphicon-plus"></i>
          <% end %>
          </div>
        </th>
      <% else %>
        <th>情報</th>
      <% end %>
    </tr>
  </thead>
  <% if @books.any? %>
  <tbody>
    <% @books.each do |b| %>
    <tr>
    <td><%= b.id %></td>
    <td><%= b.title %></td>
    <td><%= b.author %></td>
    <td><%= b.manufacturer %></td>
    <td><%= b.publication_date %></td>
    <td align="right">
        <%= link_to book_path(b.id), class: "btn btn-info" do %>
          <i class="glyphicon glyphicon-info-sign"></i>
        <% end %>

        <% if can? :update, Book %>
          <%= link_to edit_book_path(b.id), class: "btn btn-warning" do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        <% end %>

        <% if can? :destroy, Book %>
          <%= link_to book_path(b.id), method: :delete, data: { confirm: "削除してもよろしいですか？" }, :class => "btn btn-danger" do %>
            <i class="glyphicon glyphicon-remove-circle"></i>
          <% end %>
        <% end %>
    </td>
    </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

<%= paginate @books %>

app/views/books/new.html.erb
<h1>本の追加</h1>

<%= bootstrap_form_for(@book) do |f| %>
  <%= f.text_field :isbn, autofocus: true %>
  <input class="btn btn-danger" type="button" id="info_search_button" value="検索">
  <hr>
  <%= f.text_field :title %>
  <%= f.text_field :author %>
  <%= f.text_field :manufacturer %>
  <%= f.text_field :publication_date %>
  <b>Image</b>
  <div id="image-box"><img /></div>
  <br>
  <%= f.text_field :image_url %>
  <%= f.text_field :code %>
  <%= f.primary "本を追加" %>
<% end %>

app/views/books/show.html.erb
<h1>本の詳細</h1>


<table class="table table-bordered">
  <tbody>
    <tr>
    <td width="100", class="info">イメージ</td> <td><%= image_tag @book.image_url %></td>
    </tr>
    <tr>
    <td width="100", class="info">タイトル</td> <td><%= @book.title %></td>
    </tr>
    <tr>
    <td width="100", class="info">著者</td> <td><%= @book.author %></td>
    </tr>
    <tr>
    <td width="100", class="info">出版社</td> <td><%= @book.manufacturer %></td>
    </tr>
    <tr>
    <td width="100", class="info">出版日</td> <td><%= @book.publication_date %></td>
    </tr>
    <tr>
    <td width="100", class="info">ISBN</td> <td><%= @book.isbn %></td>
    </tr>
    <tr>
    <td width="100", class="info">管理番号</td> <td><%= @book.code %></td>
    </tr>
    <tr>
    <td width="100", class="info">貸出回数</td> <td><%= @book.book_rental_info.rental_count %></td>
    </tr>
    <tr>
    <td width="100", class="info">貸出状態</td> <td>未貸出</td>
    </tr>
    <tr>
    <td width="100", class="info">借りてる人</td> <td><%= @book.book_rental_info.now_rental_name %></td>
    </tr>
  </tbody>
</table>