config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :books
  resources :rentals, :only => [:index, :new, :create]
  resources :users, :only => [:index, :edit, :update, :show]
  resources :logs

  get 'search_book', to: 'rentals#search_book', path: "/rentals/new/search_book"
  get 'get_info', to: 'books#get_info', path: "/books/new/get_info"
  get 'return', to: 'rentals#pre_return', path: "/rentals/return"
  get 'search_book', to: 'rentals#search_book', path: "/rentals/return/search_book"
  post 'rentals', to: 'rentals#post_return', path: "/rentals/return"

 root 'welcome#index'

end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><%= content_for?(:title) ? yield(:title) : "Karitakke" %></title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

      <%= javascript_include_tag "application" %>

      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
      <![endif]-->
    </head>
    <body>

      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? and current_user.role != "member" %>
          <a class="navbar-brand" href="#">図書管理システム Karitakke<sup>for admin</sup></a>
          <% else %>
          <a class="navbar-brand" href="#">図書管理システム Karitakke</a>
          <% end %>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_path %></li>
              <li>
                <%= link_to rentals_path do %>
                借りている本
                <% if user_signed_in? %>
                <span class="badge">
                <%= current_user.rentals.where("is_returned = ?", false).count %>
                </span>
                <% end %>
                <% end %> 
              </li>
              <li><%= link_to "蔵書一覧", books_path  %></li>
              <% if can? :read, User%>
                <li><%= link_to "登録ユーザー管理", users_path  %></li>
              <% end %>
              <% if can? :read, Rental %>
                <li><%= link_to "ログ", logs_path  %></li>
              <% end %>
            </ul>
            <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "プロフィール変更", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "サインアウト", destroy_user_session_path, :method => :delete%></li>
                </ul>
              </li>
            </ul>
            <% end %>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "本を借りる", new_rental_path %></li>
                <li><%= link_to "本を返す", "/rentals/return"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->

          <div class="col-lg-9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <footer>
          <p>&copy; Oeda Laboratory 2015</p>
        </footer>

      </div> <!-- /container -->

    </body>
  </html>